global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8800']

  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']

  - job_name: 'uc-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['uc-service:8000']

  - job_name: 'position-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['position-service:8003']

  - job_name: 'intention-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['intention-service:8001']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8002']