spring.application.name=euruka-server

# default port for eureka server

server.port=8761

# Chính b?n thân Eureka Server, khi kh?i ??ng lên, m?c ??nh nó c?ng hành x? nh? m?t client (t?c là nó t? ??ng ký chính mình v?i chính nó).

# Ngh?a là: Không c?n ??ng ký Eureka Server vào chính nó. (Vì nó là server r?i!)

eureka.client.register-with-eureka=false

# Ngh?a là: Không c?n ?i fetch danh sách các service ?ã ??ng ký t? Eureka Server.

# (Vì nó là ng??i qu?n lý danh sách ?ó, không c?n t? ?i h?i chính mình.)

eureka.client.fetch-registry=false
