CREATE DATABASE IF NOT EXISTS qbike DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS qbike_uc DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS qbike_position DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS qbike_intention DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS qbike_order DEFAULT CHARACTER SET utf8;

USE qbike_uc;
-- Add sample data
INSERT INTO t_user (id, userName, mobile, type) VALUES 
(1, 'Customer 1', '0123456789', 'Customer'),
(2, 'Driver 1', '0987654321', 'Driver');